# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='AccionEstrategica',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreAccionEstrategica', models.CharField(max_length=100)),
                    ('unidadDeMedida', models.CharField(max_length=200)),
                    ('descripcionAccionEstrategica', models.TextField(max_length=300)),
                ],
        ),
        migrations.CreateModel(
                name='Carencia',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreCarencia', models.CharField(max_length=200)),
                ],
        ),
        migrations.CreateModel(
                name='Delegacion',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreDelegacion', models.CharField(max_length=200)),
                    ('imagenDelegacion', models.FileField(blank=True, null=True, upload_to=b'')),
                    ('fecha_ultima_modificacion', models.DateTimeField(blank=True, null=True)),
                    ('orden_secretaria', models.FloatField(blank=True, null=True)),
                    ('dependienteDe',
                     models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='djangoISSSTE.Delegacion')),
                ],
        ),
        migrations.CreateModel(
                name='Estado',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreEstado', models.CharField(max_length=200)),
                    ('latitud', models.FloatField()),
                    ('longitud', models.FloatField()),
                ],
        ),
        migrations.CreateModel(
                name='Meta',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('mes', models.CharField(max_length=200)),
                    ('cantidad', models.FloatField()),
                    ('accionEstrategica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                            to='djangoISSSTE.AccionEstrategica')),
                    ('entidad',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
                ],
        ),
        migrations.CreateModel(
                name='Municipio',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreMunicipio', models.CharField(max_length=200)),
                    ('latitud', models.FloatField()),
                    ('longitud', models.FloatField()),
                    (
                        'estado',
                        models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
                ],
        ),
        migrations.CreateModel(
                name='SubCarencia',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreSubcarencia', models.CharField(max_length=200)),
                    ('carencia',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Carencia')),
                ],
        ),
        migrations.CreateModel(
                name='UserProfile',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('rol',
                     models.CharField(choices=[(b'AD', b'Administrador general'), (b'US', b'Usuario de Dependencia')],
                                      default=b'US', max_length=2)),
                    ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='djangoISSSTE.Delegacion')),
                    ('user',
                     models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.AddField(
                model_name='meta',
                name='municipio',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Municipio'),
        ),
        migrations.AddField(
                model_name='accionestrategica',
                name='carencia',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Carencia'),
        ),
        migrations.AddField(
                model_name='accionestrategica',
                name='delegacion',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Delegacion'),
        ),
        migrations.AddField(
                model_name='accionestrategica',
                name='subcarencia',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.SubCarencia'),
        ),
    ]
