# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
                name='Delegacion',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreDelegacion', models.CharField(max_length=200)),
                    ('imagenDelegacion', models.FileField(blank=True, null=True, upload_to='')),
                    ('fecha_ultima_modificacion', models.DateTimeField(blank=True, null=True)),
                    ('orden_secretaria', models.FloatField(blank=True, null=True)),
                    ('dependienteDe',
                     models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='djangoISSSTE.Delegacion')),
                ],
        ),
        migrations.CreateModel(
                name='Estado',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreEstado', models.CharField(max_length=200)),
                    ('latitud', models.FloatField()),
                    ('longitud', models.FloatField()),
                ],
        ),
        migrations.CreateModel(
                name='Municipio',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreMunicipio', models.CharField(max_length=200)),
                    ('latitud', models.FloatField()),
                    ('longitud', models.FloatField()),
                    (
                    'estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
                ],
        ),
        migrations.CreateModel(
                name='Usuario',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('rol', models.CharField(
                        choices=[('SA', 'Administrador General'), ('FU', 'Funcionario de Dependencia'),
                                 ('AD', 'Administrador de Dependencia'), ('UD', 'Usuario de Dependencia'),
                                 ('US', 'Usuario de SubDependencia')], default='US', max_length=2)),
                    ('delegacion', models.ManyToManyField(blank=True, null=True, to='djangoISSSTE.Delegacion')),
                    ('user',
                     models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
    ]
