# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 05:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionEstrategica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAccion', models.CharField(max_length=200)),
                ('unidadDeMedida', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Acciones Estrategicas',
            },
        ),
        migrations.CreateModel(
            name='AvanceMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AvancePorMunicipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Carencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarencia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMes', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMeta', models.CharField(max_length=200)),
                ('inversionAprox', models.FloatField()),
                ('accionEstrategica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.AccionEstrategica')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='MetaMensual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Mes')),
                ('meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Meta')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMunicipio', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('estado', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePeriodo', models.IntegerField()),
            ],
            options={
                'ordering': ['nombrePeriodo'],
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreResponsable', models.CharField(max_length=100)),
                ('cargoResponsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCarencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSubCarencia', models.CharField(max_length=200)),
                ('carencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Carencia')),
            ],
            options={
                'verbose_name_plural': 'Sub Carencias',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('RE', 'Administrador Regional'), ('ES', 'Administrador Estatal')], default=django.contrib.auth.models.User, max_length=2)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meta',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Periodo'),
        ),
        migrations.AddField(
            model_name='avancepormunicipio',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Meta'),
        ),
        migrations.AddField(
            model_name='avancepormunicipio',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Municipio'),
        ),
        migrations.AddField(
            model_name='avancepormunicipio',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Periodo'),
        ),
        migrations.AddField(
            model_name='avancemensual',
            name='avancePorMunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.AvancePorMunicipio'),
        ),
        migrations.AddField(
            model_name='avancemensual',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Mes'),
        ),
        migrations.AddField(
            model_name='accionestrategica',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Responsable'),
        ),
        migrations.AddField(
            model_name='accionestrategica',
            name='subCarencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.SubCarencia'),
        ),
    ]
