# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoISSSTE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
                name='AccionEstrategica',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreAccionEstrategica', models.CharField(max_length=100)),
                    ('unidadDeMedida', models.CharField(max_length=200)),
                    ('descripcionAccionEstrategica', models.TextField(max_length=300)),
                ],
        ),
        migrations.CreateModel(
                name='AvanceMensual',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('mes', models.CharField(max_length=200)),
                    ('unidad', models.FloatField()),
                ],
        ),
        migrations.CreateModel(
                name='Carencia',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreCarencia', models.CharField(max_length=200)),
                ],
        ),
        migrations.CreateModel(
                name='Meta',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('accionEstrategica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                            to='djangoISSSTE.AccionEstrategica')),
                    ('entidad',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Estado')),
                    ('municipio',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Municipio')),
                ],
        ),
        migrations.CreateModel(
                name='SubCarencia',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('nombreSubcarencia', models.CharField(max_length=200)),
                    ('carencia',
                     models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Carencia')),
                ],
        ),
        migrations.CreateModel(
                name='UserProfile',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('rol',
                     models.CharField(choices=[('AD', 'Administrador general'), ('US', 'Usuario de Dependencia')],
                                      default='US', max_length=2)),
                    ('delegacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     to='djangoISSSTE.Delegacion')),
                    ('user',
                     models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ],
        ),
        migrations.RemoveField(
                model_name='usuario',
                name='delegacion',
        ),
        migrations.RemoveField(
                model_name='usuario',
                name='user',
        ),
        migrations.DeleteModel(
                name='Usuario',
        ),
        migrations.AddField(
                model_name='avancemensual',
                name='meta',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.Meta'),
        ),
        migrations.AddField(
                model_name='accionestrategica',
                name='subcarencia',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoISSSTE.SubCarencia'),
        ),
    ]
