# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('djangoISSSTE', '0002_auto_20160413_0217'),
    ]

    operations = [
        migrations.RemoveField(
                model_name='avancemensual',
                name='meta',
        ),
        migrations.AddField(
                model_name='meta',
                name='cantidad',
                field=models.FloatField(default=2),
                preserve_default=False,
        ),
        migrations.AddField(
                model_name='meta',
                name='mes',
                field=models.CharField(default=1, max_length=200),
                preserve_default=False,
        ),
        migrations.DeleteModel(
                name='AvanceMensual',
        ),
    ]
