# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-13 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('djangoISSSTE', '0003_auto_20160413_0239'),
    ]

    operations = [
        migrations.AddField(
                model_name='accionestrategica',
                name='carencia',
                field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                        to='djangoISSSTE.Carencia'),
                preserve_default=False,
        ),
    ]
